# Generated by Django 4.2.23 on 2026-07-10 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ders Kodu (örn: CENG201)'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('course', 'Ders Odası / Course Room'), ('project', 'Proje & Çalışma Grubu / Project Group'), ('general', 'Genel Tartışma / General Discussion')], default='general', max_length=20, verbose_name='Oda Türü'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Mühendislik ve Mimarlık Fakültesi', 'Mühendislik ve Mimarlık Fakültesi (Engineering & Architecture)'), ('İktisadi ve İdari Bilimler Fakültesi', 'İktisadi ve İdari Bilimler Fakültesi (Economics & Administrative Sciences)'), ('İnsan ve Toplum Bilimleri Fakültesi', 'İnsan ve Toplum Bilimleri Fakültesi (Humanities & Social Sciences)'), ('Sağlık Bilimleri Fakültesi', 'Sağlık Bilimleri Fakültesi (Health Sciences)'), ('Spor Bilimleri Fakültesi', 'Spor Bilimleri Fakültesi (Sports Sciences)'), ('İletişim Fakültesi', 'İletişim Fakültesi (Communication)'), ('Uygulamalı Bilimler Yüksekokulu', 'Uygulamalı Bilimler Yüksekokulu (Applied Sciences)'), ('Yabancı Diller Yüksekokulu', 'Yabancı Diller Yüksekokulu (Foreign Languages)'), ('Lisansüstü Eğitim Enstitüsü', 'Lisansüstü Eğitim Enstitüsü (Graduate School)'), ('Meslek Yüksekokulu', 'Meslek Yüksekokulu (Vocational School)'), ('Sağlık Hizmetleri Meslek Yüksekokulu', 'Sağlık Hizmetleri Meslek Yüksekokulu (Health Services Vocational School)'), ('Genel / Diğer', 'Genel / Diğer (General / Other)')], default='Genel / Diğer', max_length=100, verbose_name='Fakülte / Bölüm'),
        ),
        migrations.AddField(
            model_name='user',
            name='github_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='GitHub Profili'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn Profili'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Öğrenci / Student'), ('faculty', 'Akademisyen / Faculty Member'), ('ta', 'Asistan / Teaching Assistant')], default='student', max_length=20, verbose_name='Akademik Rol'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Öğrenci / Sicil No'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kaynak Başlığı')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/%Y/%m/', verbose_name='Dosya (PDF, ZIP, Resim)')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Bağlantı (URL)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='base.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
