# Generated by Django 4.2.23 on 2026-07-10 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_course_code_room_room_type_user_department_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Oda Açıklaması'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Çalışma Odası Adı'),
        ),
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic', verbose_name='Bölüm / Akademik Konu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='', verbose_name='Profil Fotoğrafı (Avatar)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True, verbose_name='Hakkımda (Biyografi)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Meslek Yüksekokulu (MYO)', (('Adalet', 'Adalet'), ('Aşçılık', 'Aşçılık'), ('Bilgisayar Programcılığı', 'Bilgisayar Programcılığı'), ('Dış Ticaret', 'Dış Ticaret'), ('E-Ticaret ve Pazarlama', 'E-Ticaret ve Pazarlama'), ('Grafik Tasarımı', 'Grafik Tasarımı'), ('Halkla İlişkiler ve Tanıtım', 'Halkla İlişkiler ve Tanıtım'), ('Harita ve Kadastro', 'Harita ve Kadastro'), ('İç Mekan Tasarımı', 'İç Mekan Tasarımı'), ('İnşaat Teknolojisi', 'İnşaat Teknolojisi'), ('Lojistik', 'Lojistik'), ('Mimari Restorasyon', 'Mimari Restorasyon'), ('Mahkeme Büro Hizmetleri', 'Mahkeme Büro Hizmetleri'), ('Moda ve Tekstil Tasarımı', 'Moda ve Tekstil Tasarımı'), ('Otomotiv Teknolojisi', 'Otomotiv Teknolojisi'), ('Sivil Havacılık ve Kabin Hizmetleri', 'Sivil Havacılık ve Kabin Hizmetleri'), ('Sosyal Güvenlik', 'Sosyal Güvenlik'), ('Sosyal Hizmetler (MYO)', 'Sosyal Hizmetler'), ('Spor Yönetimi (MYO)', 'Spor Yönetimi'), ('Web Tasarım ve Kodlama', 'Web Tasarım ve Kodlama'), ('Bilişim Güvenliği Teknolojisi', 'Bilişim Güvenliği Teknolojisi'))), ('Sağlık Hizmetleri Meslek Yüksekokulu (SHMYO)', (('Acil Durum ve Afet Yönetimi', 'Acil Durum ve Afet Yönetimi'), ('Ağız ve Diş Sağlığı', 'Ağız ve Diş Sağlığı'), ('Ameliyathane Hizmetleri', 'Ameliyathane Hizmetleri'), ('Anestezi', 'Anestezi'), ('Diyaliz', 'Diyaliz'), ('Diş Protez Teknolojisi', 'Diş Protez Teknolojisi'), ('Elektronörofizyoloji', 'Elektronörofizyoloji'), ('Eczane Hizmetleri', 'Eczane Hizmetleri'), ('Fizyoterapi (SHMYO)', 'Fizyoterapi'), ('Çocuk Gelişimi Programı (SHMYO)', 'Çocuk Gelişimi Programı'), ('İlk ve Acil Yardım', 'İlk ve Acil Yardım'), ('İş Sağlığı ve Güvenliği', 'İş Sağlığı ve Güvenliği'), ('İş ve Uğraşı Terapisi', 'İş ve Uğraşı Terapisi'), ('Odyometri', 'Odyometri'), ('Optisyenlik', 'Optisyenlik'), ('Ortopedik Protez ve Ortez', 'Ortopedik Protez ve Ortez'), ('Patoloji Laboratuvar Teknikleri', 'Patoloji Laboratuvar Teknikleri'), ('Radyoterapi', 'Radyoterapi'), ('Sağlık Kurumları İşletmeciliği', 'Sağlık Kurumları İşletmeciliği'), ('Tıbbi Görüntüleme Teknikleri', 'Tıbbi Görüntüleme Teknikleri'), ('Tıbbi Laboratuvar Teknikleri', 'Tıbbi Laboratuvar Teknikleri'))), ('Mühendislik ve Mimarlık Fakültesi', (('Bilgisayar Mühendisliği', 'Bilgisayar Mühendisliği'), ('Elektrik-Elektronik Mühendisliği', 'Elektrik-Elektronik Mühendisliği'), ('Gıda Mühendisliği', 'Gıda Mühendisliği'), ('Harita Mühendisliği', 'Harita Mühendisliği'), ('İç Mimarlık', 'İç Mimarlık'), ('İnşaat Mühendisliği', 'İnşaat Mühendisliği'), ('Makine Mühendisliği', 'Makine Mühendisliği'), ('Mimarlık', 'Mimarlık'))), ('Sağlık Bilimleri Fakültesi (SBF)', (('Beslenme ve Diyetetik', 'Beslenme ve Diyetetik'), ('Çocuk Gelişimi (SBF)', 'Çocuk Gelişimi'), ('Ebelik', 'Ebelik'), ('Ergoterapi', 'Ergoterapi'), ('Fizyoterapi ve Rehabilitasyon', 'Fizyoterapi ve Rehabilitasyon'), ('Hemşirelik', 'Hemşirelik'), ('Odyoloji', 'Odyoloji'), ('Sağlık Yönetimi', 'Sağlık Yönetimi'), ('Sosyal Hizmet (SBF)', 'Sosyal Hizmet'))), ('Spor Bilimleri Fakültesi', (('Antrenörlük Eğitimi', 'Antrenörlük Eğitimi'), ('Egzersiz ve Spor Bilimleri', 'Egzersiz ve Spor Bilimleri'), ('Spor Yöneticiliği', 'Spor Yöneticiliği'), ('Rekreasyon', 'Rekreasyon'))), ('İletişim Fakültesi', (('Yeni Medya ve İletişim', 'Yeni Medya ve İletişim'), ('Görsel İletişim Tasarımı', 'Görsel İletişim Tasarımı'))), ('Fen Edebiyat Fakültesi', (('İngiliz Dili ve Edebiyatı', 'İngiliz Dili ve Edebiyatı'), ('Psikoloji', 'Psikoloji'), ('Türk Dili ve Edebiyatı', 'Türk Dili ve Edebiyatı'), ('Moleküler Biyoloji ve Genetik', 'Moleküler Biyoloji ve Genetik'), ('Mütercim Tercümanlık', 'Mütercim Tercümanlık'))), ('İktisadi ve İdari Bilimler Fakültesi', (('İşletme', 'İşletme'), ('İşletme (İngilizce)', 'İşletme (İngilizce)'), ('Siyaset Bilimi ve Kamu Yönetimi', 'Siyaset Bilimi ve Kamu Yönetimi'), ('Uluslararası İlişkiler', 'Uluslararası İlişkiler'), ('Maliye', 'Maliye'))), ('Uygulamalı Bilimler Yüksekokulu', (('Gastronomi ve Mutfak Sanatları', 'Gastronomi ve Mutfak Sanatları'), ('Yönetim Bilişim Sistemleri', 'Yönetim Bilişim Sistemleri'))), ('Diğer / Genel', (('Genel / Diğer', 'Genel / Diğer'),))], default='Genel / Diğer', max_length=100, verbose_name='Fakülte / Bölüm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='E-Posta Adresi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Ad Soyad'),
        ),
    ]
