# Generated by Django 4.2.23 on 2026-07-10 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_managers_alter_room_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sınav / Test Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sınav Açıklaması ve Kurallar')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Süre (Dakika)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='base.room')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Soru Metni')),
                ('option_a', models.CharField(max_length=300, verbose_name='A Seçeneği')),
                ('option_b', models.CharField(max_length=300, verbose_name='B Seçeneği')),
                ('option_c', models.CharField(max_length=300, verbose_name='C Seçeneği')),
                ('option_d', models.CharField(max_length=300, verbose_name='D Seçeneği')),
                ('correct_option', models.CharField(choices=[('A', 'A Seçeneği'), ('B', 'B Seçeneği'), ('C', 'C Seçeneği'), ('D', 'D Seçeneği')], default='A', max_length=1, verbose_name='Doğru Cevap')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Puan')),
                ('total_questions', models.IntegerField(verbose_name='Toplam Soru')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='base.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('quiz', 'student')},
            },
        ),
    ]
