# Generated by Django 4.2.23 on 2026-07-13 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_quiz_question_quizsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ödev Başlığı')),
                ('description', models.TextField(verbose_name='Ödev Açıklaması ve Talimatlar')),
                ('deadline', models.DateTimeField(verbose_name='Son Teslim Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='base.room')),
            ],
            options={
                'ordering': ['-deadline'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='is_verified_answer',
            field=models.BooleanField(default=False, verbose_name='Öğretim Üyesi Onaylı Cevap'),
        ),
        migrations.AddField(
            model_name='resource',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Bildirim Mesajı')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bağlantı URL')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/%Y/%m/', verbose_name='Ödev Dosyası')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Öğrenci Notu')),
                ('grade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Not / Puan')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='base.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
