# Generated by Django 4.2.23 on 2026-07-14 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_assignment_message_is_verified_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='teacher_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Öğretim Üyesi Değerlendirmesi'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=10, verbose_name='Soru Puanı / Baram'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Çoktan Seçmeli (Test)'), ('essay', 'Açık Uçlu / Klasik (Yazılı)')], default='multiple_choice', max_length=20, verbose_name='Soru Tipi'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi ve Saati'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi ve Saati'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='cheat_warnings',
            field=models.PositiveIntegerField(default=0, verbose_name='Sekme Değiştirme / İhlal Sayısı'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='is_graded',
            field=models.BooleanField(default=True, verbose_name='Tamamen Puanlandı mı?'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='teacher_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Öğretim Üyesi Değerlendirme Notu'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'A Seçeneği'), ('B', 'B Seçeneği'), ('C', 'C Seçeneği'), ('D', 'D Seçeneği')], default='A', max_length=1, null=True, verbose_name='Doğru Cevap'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='A Seçeneği'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='B Seçeneği'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='C Seçeneği'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='D Seçeneği'),
        ),
        migrations.CreateModel(
            name='QuizSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('essay_answer', models.TextField(blank=True, null=True, verbose_name='Öğrencinin Yazılı Cevabı')),
                ('awarded_points', models.IntegerField(default=0, verbose_name='Kazanılan Puan')),
                ('teacher_comment', models.TextField(blank=True, null=True, verbose_name='Soruya Özel Öğretmen Notu')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='base.quizsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Konu / Başlık')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Çoktan Seçmeli (Test)'), ('essay', 'Açık Uçlu / Klasik (Yazılı)')], default='multiple_choice', max_length=20, verbose_name='Soru Tipi')),
                ('text', models.TextField(verbose_name='Soru Metni')),
                ('option_a', models.CharField(blank=True, max_length=300, null=True, verbose_name='A Seçeneği')),
                ('option_b', models.CharField(blank=True, max_length=300, null=True, verbose_name='B Seçeneği')),
                ('option_c', models.CharField(blank=True, max_length=300, null=True, verbose_name='C Seçeneği')),
                ('option_d', models.CharField(blank=True, max_length=300, null=True, verbose_name='D Seçeneği')),
                ('correct_option', models.CharField(blank=True, choices=[('A', 'A Seçeneği'), ('B', 'B Seçeneği'), ('C', 'C Seçeneği'), ('D', 'D Seçeneği')], default='A', max_length=1, null=True, verbose_name='Doğru Cevap')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Varsayılan Puan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
