# Generated by Django 4.2.23 on 2026-07-16 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyotp


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_assignmentsubmission_teacher_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('secret_key', models.CharField(default=pyotp.random_base32, max_length=32)),
                ('teacher_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Öğretmen / Sınıf IP Adresi')),
                ('require_ip_check', models.BooleanField(default=True, verbose_name='Wi-Fi IP Otomatik Yoklama')),
                ('allow_qr_check', models.BooleanField(default=True, verbose_name='QR Kod ile Yoklamaya İzin Ver')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='base.room', verbose_name='Ders Odası')),
            ],
            options={
                'verbose_name': 'Yoklama Oturumu',
                'verbose_name_plural': 'Yoklama Oturumları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='present', max_length=20, verbose_name='Durum')),
                ('client_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Öğrenci IP Adresi')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='base.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yoklama Kaydı',
                'verbose_name_plural': 'Yoklama Kayıtları',
                'ordering': ['-timestamp'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
